## ESERCIZIO NUMPY

### Notebook 02_02 - Sub-array as no copy view

Creare un array es3 di valori casuali interi (randint) di dimensione 3x3, con valore massimo (incluso) uguale a 20

In [21]:
import numpy as np

es3 = np.random.randint(21, size=(3,3))
es3

array([[10,  2, 14],
       [ 1,  7, 10],
       [17,  7, 10]])

1. estrarre il subarray formato dalla seconda riga (es3_sub) come vista e visualizzarlo
2. moltiplicare per 3 tutti gli elementi della seconda colonna di es3
3. visualizzare es3_sub. È cambiato rispetto a prima?
4. estrarre il subarray formato dalla terza colonna di es3 come copia (es3_sub_copy)
5. sommare 10 a tutti gli elementi di es3_sub_copy e visualizzare
6. visualizzare es3. Contiene la modifica del punto 6?

In [29]:
#punto1
es3_sub=es3[1,:]
#si può usare anche la forma compatta es3[1]
es3_sub

array([ 1, 63, 10])

In [30]:
#punto2
print("valori della colonna prima della moltiplicazione",es3[:,1])
es3[:,1]=es3[:,1]*3
print("valori della colonna dopo la moltiplicazione",es3[:,1])

valori della colonna prima della moltiplicazione [18 63 63]
valori della colonna dopo la moltiplicazione [ 54 189 189]


In [27]:
#punto3
es3_sub
#È cambiato? SÌ

array([ 1, 63, 10])

In [31]:
#punto4
es3_sub_copy=es3[:,2].copy()
es3_sub_copy

array([14, 10, 10])

In [32]:
#punto5
es3_sub_copy=es3_sub_copy+10
es3_sub_copy

array([24, 20, 20])

In [33]:
#punto6
es3
#Contiene la modifica fatta a es3_sub_copy? NO

array([[ 10,  54,  14],
       [  1, 189,  10],
       [ 17, 189,  10]])