## ESERCIZIO NUMPY

### Notebook 02_02 - Reshaping and Array Concatenation and Splitting

Creare una lista es4 di 36 valori interi crescenti partendo da 1

In [39]:
import numpy as np

es4 = np.arange(1,37)
es4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36])

1. Trasformarlo in un array di dimensione 6x6
2. Estrarre tre subarray di dimensione 2x2 dalle prime due colonne (sub1, sub2, sub3)
3. Concatenarli (usare concatenate) prima usando axis=0 poi con axis=1 

In [40]:
#punto1
es4=es4.reshape(6,6)
es4

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [41]:
#punto2
sub1=es4[:2,:2]
sub2=es4[2:4,:2]
sub3=es4[4:6,:2]

In [16]:
#punto3a
np.concatenate([sub1, sub2, sub3], axis=0)
#per la concatenazione in verticale, axis=0 si può omettere

array([[ 1,  2],
       [ 7,  8],
       [13, 14],
       [19, 20],
       [25, 26],
       [31, 32]])

In [17]:
#punto3b
np.concatenate([sub1, sub2, sub3], axis=1)

array([[ 1,  2, 13, 14, 25, 26],
       [ 7,  8, 19, 20, 31, 32]])

4. Da es4 estrarre un subarray formato dalle prime due righe (sub4)
5. Concatenare sub1 a sub4. Usate hstack o vstack?
6. Trasformate sub4 da 2x6 a 6x2 (le 2 righe diventano 2 colonne)
7. Concatenate sub1, sub2 e sub3 a formare un nuovo array 6x2 (sub5)
8. Concatenate sub4 (trasformato) con sub5. hstack o vstack?

In [31]:
#punto4
sub4=es4[:2,:]

In [22]:
#punto5
# provare np.concatenate([sub1, sub4], axis=0), funziona? perché?
np.hstack([sub1, sub4])

array([[ 1,  2,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  7,  8,  9, 10, 11, 12]])

In [32]:
#punto 6
print("sub4 prima di reshape:\n", sub4, "\n")
sub4=sub4.reshape(6,2)
print("sub4 dopo il reshape:\n", sub4)

sub4 prima di reshape:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]] 

sub4 dopo il reshape:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [35]:
#punto7
sub5=np.vstack([sub1,sub2,sub3])
sub5

array([[ 1,  2],
       [ 7,  8],
       [13, 14],
       [19, 20],
       [25, 26],
       [31, 32]])

In [38]:
#punto8: sub4 è 6x2, sub5 anche è 6x2. Possiamo concatenarli sia orizzontalmente sia verticalmente
print("Concateno verticalmente:\n", np.vstack([sub4,sub5]), "\n")
print("Concateno orizzontalmente:\n", np.hstack([sub4,sub5]))

Concateno verticalmente:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [ 1  2]
 [ 7  8]
 [13 14]
 [19 20]
 [25 26]
 [31 32]] 

Concateno orizzontalmente:
 [[ 1  2  1  2]
 [ 3  4  7  8]
 [ 5  6 13 14]
 [ 7  8 19 20]
 [ 9 10 25 26]
 [11 12 31 32]]
